version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
http:
  addr: localhost:5000
  net: tcp
  debug:
    addr: localhost:5001
  headers:
    X-Content-Type-Options: [nosniff]
  http2:
    disabled: false