version: '3.3'

services:
  streaming:
    image: limpidkzonix/nginx-streaming-server:latest
    ports:
      - "7890:7890/tcp"
      - "7890:7890/udp"
      - "1936:1935/tcp"
      - "1936:1935/udp"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.tcp.routers.streaming.service=streaming-service
        - traefik.tcp.services.streaming-service.loadbalancer.server.port=1936
        - traefik.docker.network=traefik-public

networks:
  traefik-public:
    external: true