version: "3"
 
services:
 
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy.conf:/etc/nginx/proxy.conf
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 2
        delay: 10s